apiVersion: v1
kind: List
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: edge-router
    spec: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: front-end
    spec: {}
